//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource1", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br/&gt; Password and Confirm password must be same..
        /// </summary>
        internal static string cvr_message {
            get {
                return ResourceManager.GetString("cvr_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exist..
        /// </summary>
        internal static string Duplicate_User {
            get {
                return ResourceManager.GetString("Duplicate_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password..
        /// </summary>
        internal static string Invalid_Pwd {
            get {
                return ResourceManager.GetString("Invalid_Pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Does not exist..
        /// </summary>
        internal static string Invalid_User {
            get {
                return ResourceManager.GetString("Invalid_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Record is added successfully..
        /// </summary>
        internal static string RecordAdded {
            get {
                return ResourceManager.GetString("RecordAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Record is delelted successfully..
        /// </summary>
        internal static string RecordDeleted {
            get {
                return ResourceManager.GetString("RecordDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorMessage..
        /// </summary>
        internal static string RecordFailure {
            get {
                return ResourceManager.GetString("RecordFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Record is updated successfully..
        /// </summary>
        internal static string RecordUpdated {
            get {
                return ResourceManager.GetString("RecordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email Id..
        /// </summary>
        internal static string rev_email_message {
            get {
                return ResourceManager.GetString("rev_email_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required field..
        /// </summary>
        internal static string rfv_message {
            get {
                return ResourceManager.GetString("rfv_message", resourceCulture);
            }
        }
    }
}
